name: Node.js CI

on:
  # Vai rodar quando for aberto um PR para a branch develop
  pull_request:
    branches:
      - develop

  # Vai rodar quando for feito um push na branch develop
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Enable Corepack
        run: |
          corepack enable
          corepack yarn install

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Enable Corepack
        run: |
          corepack enable
          corepack yarn install

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test

  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Enable Corepack
        run: |
          corepack enable
          corepack yarn install

      - name: Install dependencies
        run: yarn install

      - name: SonarQube Analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
